export const MOCK_CATEGORIES = [
  {
    _id: "1",
    title: "NEW ARRIVALS",
    slug: { current: "new-arrivals" },
    image: "/assets/cat-new.png", // Placeholder path
  },
  {
    _id: "2",
    title: "OUTERWEAR",
    slug: { current: "outerwear" },
    image: "/assets/cat-outerwear.png",
  },
  {
    _id: "3",
    title: "TOPS",
    slug: { current: "tops" },
    image: "/assets/cat-tops.png",
  },
  {
    _id: "4",
    title: "BOTTOMS",
    slug: { current: "bottoms" },
    image: "/assets/cat-bottoms.png",
  },
  {
    _id: "5",
    title: "PERFORMANCE LINE",
    slug: { current: "performance-line" },
    image: "/assets/cat-performance.png",
  },
  {
    _id: "6",
    title: "LIMITED DROP",
    slug: { current: "limited-drop" },
    image: "/assets/cat-limited.png",
  },
  {
    _id: "7",
    title: "ESSENTIALS",
    slug: { current: "essentials" },
    image: "/assets/cat-essentials.png",
  },
  {
    _id: "8",
    title: "ACCESSORIES",
    slug: { current: "accessories" },
    image: "/assets/cat-accessories.png",
  },
];

export const MOCK_PRODUCTS = [
  {
    _id: "101",
    title: "NEURAL HOODIE",
    price: 95.0,
    rowPrice: 120.0,
    slug: { current: "neural-hoodie" },
    image: "/assets/prod-hoodie.png",
    description:
      "Heavyweight fleece / 450GSM. Engineered for warmth and structure.",
    category: "tops",
    isNew: true,
  },
  {
    _id: "102",
    title: "IMPACT TEE",
    price: 55.0,
    rowPrice: 70.0,
    slug: { current: "impact-tee" },
    image: "/assets/prod-tee.png",
    description: "300GSM Cotton / Boxy Fit. Breathable structure.",
    category: "tops",
  },
  {
    _id: "103",
    title: "APEX SHELL",
    price: 210.0,
    rowPrice: 250.0,
    slug: { current: "apex-shell" },
    image: "/assets/prod-shell.png",
    description: "Ripstop Tech / Breathable. Water-resistant outer layer.",
    category: "outerwear",
    isPerformance: true,
  },
  {
    _id: "104",
    title: "MOTION UTILITY PANT",
    price: 120.0,
    slug: { current: "motion-utility-pant" },
    image: "/assets/prod-pants.png",
    description: "Water-Repellent Nylon. Articulated knees for movement.",
    category: "bottoms",
  },
  {
    _id: "105",
    title: "VOID TACTICAL CAP",
    price: 45.0,
    slug: { current: "void-tactical-cap" },
    image: "/assets/prod-cap.png",
    description: "Reinforced Canvas / Adjustable. Minimal branding.",
    category: "accessories",
  },
  {
    _id: "106",
    title: "STRUCTURAL OVERSHIRT",
    price: 155.0,
    slug: { current: "structural-overshirt" },
    image: "/assets/prod-overshirt.png",
    description: "Heavy Twill / Reinforced. Layering essential.",
    category: "tops",
    isLimited: true,
  },
];
