export const MOCK_CATEGORIES = [
  {
    _id: "1",
    title: "NEW ARRIVALS",
    slug: { current: "new-arrivals" },
    image: "/product-1.png", 
  },
  {
    _id: "2",
    title: "OUTERWEAR",
    slug: { current: "outerwear" },
    image: "/product-2.png",
  },
  {
    _id: "3",
    title: "TOPS",
    slug: { current: "tops" },
    image: "/product-3.png",
  },
  {
    _id: "4",
    title: "BOTTOMS",
    slug: { current: "bottoms" },
    image: "/product-4.png",
  },
  {
    _id: "5",
    title: "EVERYDAY ESSENTIALS",
    slug: { current: "essentials" },
    image: "/product-5.png",
  },
  {
    _id: "6",
    title: "LIMITED DROP",
    slug: { current: "limited-drop" },
    image: "/product-6.png",
  },
  {
    _id: "7",
    title: "ACCESSORIES",
    slug: { current: "accessories" },
    image: "/product-7.png",
  },
];

export const MOCK_PRODUCTS = [
  {
    _id: "101",
    title: "NEURAL HOODIE",
    price: 95.0,
    rowPrice: 120.0,
    slug: { current: "neural-hoodie" },
    image: "/product-1.png",
    description:
      "A clean silhouette designed for all-day comfort and easy styling. Crafted with soft, durable fabric and a fit that feels just right from the first wear. Heavyweight fleece / 450GSM.",
    category: "tops",
    isNew: true,
  },
  {
    _id: "102",
    title: "IMPACT TEE",
    price: 55.0,
    rowPrice: 70.0,
    slug: { current: "impact-tee" },
    image: "/product-2.png",
    description: "Modern streetwear essential. Boxy Fit, 300GSM Cotton. Breathable structure for everyday wear.",
    category: "tops",
  },
  {
    _id: "103",
    title: "APEX SHELL",
    price: 210.0,
    rowPrice: 250.0,
    slug: { current: "apex-shell" },
    image: "/product-3.png",
    description: "Ripstop Tech / Breathable. Water-resistant outer layer designed for movement and presence.",
    category: "outerwear",
    isPerformance: true,
  },
  {
    _id: "104",
    title: "MOTION UTILITY PANT",
    price: 120.0,
    slug: { current: "motion-utility-pant" },
    image: "/product-4.png",
    description: "Water-Repellent Nylon. Articulated knees for movement. The perfect daily rotation piece.",
    category: "bottoms",
  },
  {
    _id: "105",
    title: "VOID TACTICAL CAP",
    price: 45.0,
    slug: { current: "void-tactical-cap" },
    image: "/product-5.png",
    description: "Reinforced Canvas / Adjustable. Minimal branding for versatile, confident looks.",
    category: "accessories",
  },
  {
    _id: "106",
    title: "STRUCTURAL OVERSHIRT",
    price: 155.0,
    slug: { current: "structural-overshirt" },
    image: "/product-6.png",
    description: "Heavy Twill / Reinforced. Effortless styling piece for day to night.",
    category: "tops",
    isLimited: true,
  },
];
